-- Aerospace Supplier Scoring SQL
-- Generated from scoring.yaml and negative_signals.yaml

-- Scored view for planet_osm_point
CREATE OR REPLACE VIEW public.planet_osm_point_aerospace_scored AS
SELECT *,
    (
        CASE
        WHEN ((LOWER(name) LIKE LOWER('%aerospace%') OR LOWER(name) LIKE LOWER('%aviation%') OR LOWER(name) LIKE LOWER('%aircraft%') OR LOWER(name) LIKE LOWER('%airbus%') OR LOWER(name) LIKE LOWER('%boeing%') OR LOWER(name) LIKE LOWER('%bae%') OR LOWER(name) LIKE LOWER('%rolls royce%') OR LOWER(name) LIKE LOWER('%safran%') OR LOWER(name) LIKE LOWER('%leonardo%') OR LOWER(name) LIKE LOWER('%thales%')) OR (LOWER(operator) LIKE LOWER('%aerospace%') OR LOWER(operator) LIKE LOWER('%aviation%') OR LOWER(operator) LIKE LOWER('%aircraft%')) OR office IN ('aerospace', 'aviation')) THEN 100
        WHEN ((LOWER(name) LIKE LOWER('%defense%') OR LOWER(name) LIKE LOWER('%defence%') OR LOWER(name) LIKE LOWER('%military%') OR LOWER(name) LIKE LOWER('%radar%') OR LOWER(name) LIKE LOWER('%missile%') OR LOWER(name) LIKE LOWER('%weapons%')) OR military IS NOT NULL OR landuse IN ('military')) THEN 80
        WHEN ((LOWER(name) LIKE LOWER('%engineering%') OR LOWER(name) LIKE LOWER('%technology%') OR LOWER(name) LIKE LOWER('%systems%') OR LOWER(name) LIKE LOWER('%electronics%') OR LOWER(name) LIKE LOWER('%precision%') OR LOWER(name) LIKE LOWER('%advanced%')) OR man_made IN ('works', 'factory') OR office IN ('engineering', 'research', 'technology')) THEN 70
        WHEN (landuse IN ('industrial')) THEN 50
        WHEN ((LOWER(name) LIKE LOWER('%research%') OR LOWER(name) LIKE LOWER('%development%') OR LOWER(name) LIKE LOWER('%laboratory%') OR LOWER(name) LIKE LOWER('%institute%') OR LOWER(name) LIKE LOWER('%university%')) OR office IN ('research', 'engineering') OR amenity IN ('research_institute', 'university')) THEN 60
        ELSE 0
    END +
        CASE WHEN ((LOWER(name) LIKE LOWER('%boeing%') OR LOWER(name) LIKE LOWER('%airbus%') OR LOWER(name) LIKE LOWER('%rolls royce%') OR LOWER(name) LIKE LOWER('%bae systems%') OR LOWER(name) LIKE LOWER('%leonardo%') OR LOWER(name) LIKE LOWER('%thales%') OR LOWER(name) LIKE LOWER('%safran%')) OR (LOWER(operator) LIKE LOWER('%boeing%') OR LOWER(operator) LIKE LOWER('%airbus%') OR LOWER(operator) LIKE LOWER('%rolls royce%') OR LOWER(operator) LIKE LOWER('%bae systems%') OR LOWER(operator) LIKE LOWER('%leonardo%') OR LOWER(operator) LIKE LOWER('%thales%') OR LOWER(operator) LIKE LOWER('%safran%'))) THEN 50 ELSE 0 END +
        CASE WHEN ((LOWER(name) LIKE LOWER('%aerospace%') OR LOWER(name) LIKE LOWER('%aviation%') OR LOWER(name) LIKE LOWER('%aircraft%') OR LOWER(name) LIKE LOWER('%avionics%') OR LOWER(name) LIKE LOWER('%turbine%') OR LOWER(name) LIKE LOWER('%engine%')) OR (LOWER(operator) LIKE LOWER('%aerospace%') OR LOWER(operator) LIKE LOWER('%aviation%') OR LOWER(operator) LIKE LOWER('%aircraft%') OR LOWER(operator) LIKE LOWER('%avionics%') OR LOWER(operator) LIKE LOWER('%turbine%') OR LOWER(operator) LIKE LOWER('%engine%'))) THEN 30 ELSE 0 END +
        CASE WHEN ((LOWER(name) LIKE LOWER('%precision%') OR LOWER(name) LIKE LOWER('%machining%') OR LOWER(name) LIKE LOWER('%casting%') OR LOWER(name) LIKE LOWER('%forging%') OR LOWER(name) LIKE LOWER('%composite%') OR LOWER(name) LIKE LOWER('%materials%')) OR (LOWER(operator) LIKE LOWER('%precision%') OR LOWER(operator) LIKE LOWER('%machining%') OR LOWER(operator) LIKE LOWER('%casting%') OR LOWER(operator) LIKE LOWER('%forging%') OR LOWER(operator) LIKE LOWER('%composite%') OR LOWER(operator) LIKE LOWER('%materials%'))) THEN 20 ELSE 0 END +
        CASE WHEN (amenity IN ('restaurant', 'pub', 'cafe', 'bar', 'fast_food', 'fuel', 'hospital', 'school') OR shop IS NOT NULL OR tourism IS NOT NULL OR leisure IS NOT NULL) THEN -50 ELSE 0 END +
        CASE WHEN (landuse IN ('residential', 'retail', 'commercial', 'farmland')) THEN -25 ELSE 0 END +
        CASE WHEN (office IN ('insurance', 'finance', 'estate_agent', 'lawyer', 'accountant') OR amenity IN ('bank', 'post_office', 'library')) THEN -15 ELSE 0 END
    ) AS aerospace_score,
    ARRAY[]::text[] AS matched_keywords,
    'planet_osm_point' AS source_table
FROM public.planet_osm_point_aerospace_filtered
WHERE (
    (
        CASE
        WHEN ((LOWER(name) LIKE LOWER('%aerospace%') OR LOWER(name) LIKE LOWER('%aviation%') OR LOWER(name) LIKE LOWER('%aircraft%') OR LOWER(name) LIKE LOWER('%airbus%') OR LOWER(name) LIKE LOWER('%boeing%') OR LOWER(name) LIKE LOWER('%bae%') OR LOWER(name) LIKE LOWER('%rolls royce%') OR LOWER(name) LIKE LOWER('%safran%') OR LOWER(name) LIKE LOWER('%leonardo%') OR LOWER(name) LIKE LOWER('%thales%')) OR (LOWER(operator) LIKE LOWER('%aerospace%') OR LOWER(operator) LIKE LOWER('%aviation%') OR LOWER(operator) LIKE LOWER('%aircraft%')) OR office IN ('aerospace', 'aviation')) THEN 100
        WHEN ((LOWER(name) LIKE LOWER('%defense%') OR LOWER(name) LIKE LOWER('%defence%') OR LOWER(name) LIKE LOWER('%military%') OR LOWER(name) LIKE LOWER('%radar%') OR LOWER(name) LIKE LOWER('%missile%') OR LOWER(name) LIKE LOWER('%weapons%')) OR military IS NOT NULL OR landuse IN ('military')) THEN 80
        WHEN ((LOWER(name) LIKE LOWER('%engineering%') OR LOWER(name) LIKE LOWER('%technology%') OR LOWER(name) LIKE LOWER('%systems%') OR LOWER(name) LIKE LOWER('%electronics%') OR LOWER(name) LIKE LOWER('%precision%') OR LOWER(name) LIKE LOWER('%advanced%')) OR man_made IN ('works', 'factory') OR office IN ('engineering', 'research', 'technology')) THEN 70
        WHEN (landuse IN ('industrial')) THEN 50
        WHEN ((LOWER(name) LIKE LOWER('%research%') OR LOWER(name) LIKE LOWER('%development%') OR LOWER(name) LIKE LOWER('%laboratory%') OR LOWER(name) LIKE LOWER('%institute%') OR LOWER(name) LIKE LOWER('%university%')) OR office IN ('research', 'engineering') OR amenity IN ('research_institute', 'university')) THEN 60
        ELSE 0
    END +
        CASE WHEN ((LOWER(name) LIKE LOWER('%boeing%') OR LOWER(name) LIKE LOWER('%airbus%') OR LOWER(name) LIKE LOWER('%rolls royce%') OR LOWER(name) LIKE LOWER('%bae systems%') OR LOWER(name) LIKE LOWER('%leonardo%') OR LOWER(name) LIKE LOWER('%thales%') OR LOWER(name) LIKE LOWER('%safran%')) OR (LOWER(operator) LIKE LOWER('%boeing%') OR LOWER(operator) LIKE LOWER('%airbus%') OR LOWER(operator) LIKE LOWER('%rolls royce%') OR LOWER(operator) LIKE LOWER('%bae systems%') OR LOWER(operator) LIKE LOWER('%leonardo%') OR LOWER(operator) LIKE LOWER('%thales%') OR LOWER(operator) LIKE LOWER('%safran%'))) THEN 50 ELSE 0 END +
        CASE WHEN ((LOWER(name) LIKE LOWER('%aerospace%') OR LOWER(name) LIKE LOWER('%aviation%') OR LOWER(name) LIKE LOWER('%aircraft%') OR LOWER(name) LIKE LOWER('%avionics%') OR LOWER(name) LIKE LOWER('%turbine%') OR LOWER(name) LIKE LOWER('%engine%')) OR (LOWER(operator) LIKE LOWER('%aerospace%') OR LOWER(operator) LIKE LOWER('%aviation%') OR LOWER(operator) LIKE LOWER('%aircraft%') OR LOWER(operator) LIKE LOWER('%avionics%') OR LOWER(operator) LIKE LOWER('%turbine%') OR LOWER(operator) LIKE LOWER('%engine%'))) THEN 30 ELSE 0 END +
        CASE WHEN ((LOWER(name) LIKE LOWER('%precision%') OR LOWER(name) LIKE LOWER('%machining%') OR LOWER(name) LIKE LOWER('%casting%') OR LOWER(name) LIKE LOWER('%forging%') OR LOWER(name) LIKE LOWER('%composite%') OR LOWER(name) LIKE LOWER('%materials%')) OR (LOWER(operator) LIKE LOWER('%precision%') OR LOWER(operator) LIKE LOWER('%machining%') OR LOWER(operator) LIKE LOWER('%casting%') OR LOWER(operator) LIKE LOWER('%forging%') OR LOWER(operator) LIKE LOWER('%composite%') OR LOWER(operator) LIKE LOWER('%materials%'))) THEN 20 ELSE 0 END +
        CASE WHEN (amenity IN ('restaurant', 'pub', 'cafe', 'bar', 'fast_food', 'fuel', 'hospital', 'school') OR shop IS NOT NULL OR tourism IS NOT NULL OR leisure IS NOT NULL) THEN -50 ELSE 0 END +
        CASE WHEN (landuse IN ('residential', 'retail', 'commercial', 'farmland')) THEN -25 ELSE 0 END +
        CASE WHEN (office IN ('insurance', 'finance', 'estate_agent', 'lawyer', 'accountant') OR amenity IN ('bank', 'post_office', 'library')) THEN -15 ELSE 0 END
    )
) > 0;

-- Scored view for planet_osm_line
CREATE OR REPLACE VIEW public.planet_osm_line_aerospace_scored AS
SELECT *,
    (
        CASE
        WHEN ((LOWER(name) LIKE LOWER('%aerospace%') OR LOWER(name) LIKE LOWER('%aviation%') OR LOWER(name) LIKE LOWER('%aircraft%') OR LOWER(name) LIKE LOWER('%airbus%') OR LOWER(name) LIKE LOWER('%boeing%') OR LOWER(name) LIKE LOWER('%bae%') OR LOWER(name) LIKE LOWER('%rolls royce%') OR LOWER(name) LIKE LOWER('%safran%') OR LOWER(name) LIKE LOWER('%leonardo%') OR LOWER(name) LIKE LOWER('%thales%')) OR (LOWER(operator) LIKE LOWER('%aerospace%') OR LOWER(operator) LIKE LOWER('%aviation%') OR LOWER(operator) LIKE LOWER('%aircraft%')) OR office IN ('aerospace', 'aviation')) THEN 100
        WHEN ((LOWER(name) LIKE LOWER('%defense%') OR LOWER(name) LIKE LOWER('%defence%') OR LOWER(name) LIKE LOWER('%military%') OR LOWER(name) LIKE LOWER('%radar%') OR LOWER(name) LIKE LOWER('%missile%') OR LOWER(name) LIKE LOWER('%weapons%')) OR military IS NOT NULL OR landuse IN ('military')) THEN 80
        WHEN ((LOWER(name) LIKE LOWER('%engineering%') OR LOWER(name) LIKE LOWER('%technology%') OR LOWER(name) LIKE LOWER('%systems%') OR LOWER(name) LIKE LOWER('%electronics%') OR LOWER(name) LIKE LOWER('%precision%') OR LOWER(name) LIKE LOWER('%advanced%')) OR industrial IN ('engineering', 'electronics', 'precision', 'high_tech') OR man_made IN ('works', 'factory') OR office IN ('engineering', 'research', 'technology') OR building IN ('industrial', 'factory', 'warehouse')) THEN 70
        WHEN (landuse IN ('industrial') OR building IN ('industrial', 'warehouse', 'manufacture') OR industrial IS NOT NULL) THEN 50
        WHEN ((LOWER(name) LIKE LOWER('%research%') OR LOWER(name) LIKE LOWER('%development%') OR LOWER(name) LIKE LOWER('%laboratory%') OR LOWER(name) LIKE LOWER('%institute%') OR LOWER(name) LIKE LOWER('%university%')) OR office IN ('research', 'engineering') OR amenity IN ('research_institute', 'university')) THEN 60
        ELSE 0
    END +
        CASE WHEN ((LOWER(name) LIKE LOWER('%boeing%') OR LOWER(name) LIKE LOWER('%airbus%') OR LOWER(name) LIKE LOWER('%rolls royce%') OR LOWER(name) LIKE LOWER('%bae systems%') OR LOWER(name) LIKE LOWER('%leonardo%') OR LOWER(name) LIKE LOWER('%thales%') OR LOWER(name) LIKE LOWER('%safran%')) OR (LOWER(operator) LIKE LOWER('%boeing%') OR LOWER(operator) LIKE LOWER('%airbus%') OR LOWER(operator) LIKE LOWER('%rolls royce%') OR LOWER(operator) LIKE LOWER('%bae systems%') OR LOWER(operator) LIKE LOWER('%leonardo%') OR LOWER(operator) LIKE LOWER('%thales%') OR LOWER(operator) LIKE LOWER('%safran%'))) THEN 50 ELSE 0 END +
        CASE WHEN ((LOWER(name) LIKE LOWER('%aerospace%') OR LOWER(name) LIKE LOWER('%aviation%') OR LOWER(name) LIKE LOWER('%aircraft%') OR LOWER(name) LIKE LOWER('%avionics%') OR LOWER(name) LIKE LOWER('%turbine%') OR LOWER(name) LIKE LOWER('%engine%')) OR (LOWER(operator) LIKE LOWER('%aerospace%') OR LOWER(operator) LIKE LOWER('%aviation%') OR LOWER(operator) LIKE LOWER('%aircraft%') OR LOWER(operator) LIKE LOWER('%avionics%') OR LOWER(operator) LIKE LOWER('%turbine%') OR LOWER(operator) LIKE LOWER('%engine%'))) THEN 30 ELSE 0 END +
        CASE WHEN ((LOWER(name) LIKE LOWER('%precision%') OR LOWER(name) LIKE LOWER('%machining%') OR LOWER(name) LIKE LOWER('%casting%') OR LOWER(name) LIKE LOWER('%forging%') OR LOWER(name) LIKE LOWER('%composite%') OR LOWER(name) LIKE LOWER('%materials%')) OR (LOWER(operator) LIKE LOWER('%precision%') OR LOWER(operator) LIKE LOWER('%machining%') OR LOWER(operator) LIKE LOWER('%casting%') OR LOWER(operator) LIKE LOWER('%forging%') OR LOWER(operator) LIKE LOWER('%composite%') OR LOWER(operator) LIKE LOWER('%materials%'))) THEN 20 ELSE 0 END +
        CASE WHEN (amenity IN ('restaurant', 'pub', 'cafe', 'bar', 'fast_food', 'fuel', 'hospital', 'school') OR shop IS NOT NULL OR tourism IS NOT NULL OR leisure IS NOT NULL OR building IN ('house', 'apartments', 'residential', 'hotel', 'retail')) THEN -50 ELSE 0 END +
        CASE WHEN (landuse IN ('residential', 'retail', 'commercial', 'farmland')) THEN -25 ELSE 0 END +
        CASE WHEN (office IN ('insurance', 'finance', 'estate_agent', 'lawyer', 'accountant') OR amenity IN ('bank', 'post_office', 'library')) THEN -15 ELSE 0 END
    ) AS aerospace_score,
    ARRAY[]::text[] AS matched_keywords,
    'planet_osm_line' AS source_table
FROM public.planet_osm_line_aerospace_filtered
WHERE (
    (
        CASE
        WHEN ((LOWER(name) LIKE LOWER('%aerospace%') OR LOWER(name) LIKE LOWER('%aviation%') OR LOWER(name) LIKE LOWER('%aircraft%') OR LOWER(name) LIKE LOWER('%airbus%') OR LOWER(name) LIKE LOWER('%boeing%') OR LOWER(name) LIKE LOWER('%bae%') OR LOWER(name) LIKE LOWER('%rolls royce%') OR LOWER(name) LIKE LOWER('%safran%') OR LOWER(name) LIKE LOWER('%leonardo%') OR LOWER(name) LIKE LOWER('%thales%')) OR (LOWER(operator) LIKE LOWER('%aerospace%') OR LOWER(operator) LIKE LOWER('%aviation%') OR LOWER(operator) LIKE LOWER('%aircraft%')) OR office IN ('aerospace', 'aviation')) THEN 100
        WHEN ((LOWER(name) LIKE LOWER('%defense%') OR LOWER(name) LIKE LOWER('%defence%') OR LOWER(name) LIKE LOWER('%military%') OR LOWER(name) LIKE LOWER('%radar%') OR LOWER(name) LIKE LOWER('%missile%') OR LOWER(name) LIKE LOWER('%weapons%')) OR military IS NOT NULL OR landuse IN ('military')) THEN 80
        WHEN ((LOWER(name) LIKE LOWER('%engineering%') OR LOWER(name) LIKE LOWER('%technology%') OR LOWER(name) LIKE LOWER('%systems%') OR LOWER(name) LIKE LOWER('%electronics%') OR LOWER(name) LIKE LOWER('%precision%') OR LOWER(name) LIKE LOWER('%advanced%')) OR industrial IN ('engineering', 'electronics', 'precision', 'high_tech') OR man_made IN ('works', 'factory') OR office IN ('engineering', 'research', 'technology') OR building IN ('industrial', 'factory', 'warehouse')) THEN 70
        WHEN (landuse IN ('industrial') OR building IN ('industrial', 'warehouse', 'manufacture') OR industrial IS NOT NULL) THEN 50
        WHEN ((LOWER(name) LIKE LOWER('%research%') OR LOWER(name) LIKE LOWER('%development%') OR LOWER(name) LIKE LOWER('%laboratory%') OR LOWER(name) LIKE LOWER('%institute%') OR LOWER(name) LIKE LOWER('%university%')) OR office IN ('research', 'engineering') OR amenity IN ('research_institute', 'university')) THEN 60
        ELSE 0
    END +
        CASE WHEN ((LOWER(name) LIKE LOWER('%boeing%') OR LOWER(name) LIKE LOWER('%airbus%') OR LOWER(name) LIKE LOWER('%rolls royce%') OR LOWER(name) LIKE LOWER('%bae systems%') OR LOWER(name) LIKE LOWER('%leonardo%') OR LOWER(name) LIKE LOWER('%thales%') OR LOWER(name) LIKE LOWER('%safran%')) OR (LOWER(operator) LIKE LOWER('%boeing%') OR LOWER(operator) LIKE LOWER('%airbus%') OR LOWER(operator) LIKE LOWER('%rolls royce%') OR LOWER(operator) LIKE LOWER('%bae systems%') OR LOWER(operator) LIKE LOWER('%leonardo%') OR LOWER(operator) LIKE LOWER('%thales%') OR LOWER(operator) LIKE LOWER('%safran%'))) THEN 50 ELSE 0 END +
        CASE WHEN ((LOWER(name) LIKE LOWER('%aerospace%') OR LOWER(name) LIKE LOWER('%aviation%') OR LOWER(name) LIKE LOWER('%aircraft%') OR LOWER(name) LIKE LOWER('%avionics%') OR LOWER(name) LIKE LOWER('%turbine%') OR LOWER(name) LIKE LOWER('%engine%')) OR (LOWER(operator) LIKE LOWER('%aerospace%') OR LOWER(operator) LIKE LOWER('%aviation%') OR LOWER(operator) LIKE LOWER('%aircraft%') OR LOWER(operator) LIKE LOWER('%avionics%') OR LOWER(operator) LIKE LOWER('%turbine%') OR LOWER(operator) LIKE LOWER('%engine%'))) THEN 30 ELSE 0 END +
        CASE WHEN ((LOWER(name) LIKE LOWER('%precision%') OR LOWER(name) LIKE LOWER('%machining%') OR LOWER(name) LIKE LOWER('%casting%') OR LOWER(name) LIKE LOWER('%forging%') OR LOWER(name) LIKE LOWER('%composite%') OR LOWER(name) LIKE LOWER('%materials%')) OR (LOWER(operator) LIKE LOWER('%precision%') OR LOWER(operator) LIKE LOWER('%machining%') OR LOWER(operator) LIKE LOWER('%casting%') OR LOWER(operator) LIKE LOWER('%forging%') OR LOWER(operator) LIKE LOWER('%composite%') OR LOWER(operator) LIKE LOWER('%materials%'))) THEN 20 ELSE 0 END +
        CASE WHEN (amenity IN ('restaurant', 'pub', 'cafe', 'bar', 'fast_food', 'fuel', 'hospital', 'school') OR shop IS NOT NULL OR tourism IS NOT NULL OR leisure IS NOT NULL OR building IN ('house', 'apartments', 'residential', 'hotel', 'retail')) THEN -50 ELSE 0 END +
        CASE WHEN (landuse IN ('residential', 'retail', 'commercial', 'farmland')) THEN -25 ELSE 0 END +
        CASE WHEN (office IN ('insurance', 'finance', 'estate_agent', 'lawyer', 'accountant') OR amenity IN ('bank', 'post_office', 'library')) THEN -15 ELSE 0 END
    )
) > 0;

-- Scored view for planet_osm_polygon
CREATE OR REPLACE VIEW public.planet_osm_polygon_aerospace_scored AS
SELECT *,
    (
        CASE
        WHEN ((LOWER(name) LIKE LOWER('%aerospace%') OR LOWER(name) LIKE LOWER('%aviation%') OR LOWER(name) LIKE LOWER('%aircraft%') OR LOWER(name) LIKE LOWER('%airbus%') OR LOWER(name) LIKE LOWER('%boeing%') OR LOWER(name) LIKE LOWER('%bae%') OR LOWER(name) LIKE LOWER('%rolls royce%') OR LOWER(name) LIKE LOWER('%safran%') OR LOWER(name) LIKE LOWER('%leonardo%') OR LOWER(name) LIKE LOWER('%thales%')) OR (LOWER(operator) LIKE LOWER('%aerospace%') OR LOWER(operator) LIKE LOWER('%aviation%') OR LOWER(operator) LIKE LOWER('%aircraft%')) OR office IN ('aerospace', 'aviation')) THEN 100
        WHEN ((LOWER(name) LIKE LOWER('%defense%') OR LOWER(name) LIKE LOWER('%defence%') OR LOWER(name) LIKE LOWER('%military%') OR LOWER(name) LIKE LOWER('%radar%') OR LOWER(name) LIKE LOWER('%missile%') OR LOWER(name) LIKE LOWER('%weapons%')) OR military IS NOT NULL OR landuse IN ('military')) THEN 80
        WHEN ((LOWER(name) LIKE LOWER('%engineering%') OR LOWER(name) LIKE LOWER('%technology%') OR LOWER(name) LIKE LOWER('%systems%') OR LOWER(name) LIKE LOWER('%electronics%') OR LOWER(name) LIKE LOWER('%precision%') OR LOWER(name) LIKE LOWER('%advanced%')) OR industrial IN ('engineering', 'electronics', 'precision', 'high_tech') OR man_made IN ('works', 'factory') OR office IN ('engineering', 'research', 'technology') OR building IN ('industrial', 'factory', 'warehouse')) THEN 70
        WHEN (landuse IN ('industrial') OR building IN ('industrial', 'warehouse', 'manufacture') OR industrial IS NOT NULL) THEN 50
        WHEN ((LOWER(name) LIKE LOWER('%research%') OR LOWER(name) LIKE LOWER('%development%') OR LOWER(name) LIKE LOWER('%laboratory%') OR LOWER(name) LIKE LOWER('%institute%') OR LOWER(name) LIKE LOWER('%university%')) OR office IN ('research', 'engineering') OR amenity IN ('research_institute', 'university')) THEN 60
        ELSE 0
    END +
        CASE WHEN ((LOWER(name) LIKE LOWER('%boeing%') OR LOWER(name) LIKE LOWER('%airbus%') OR LOWER(name) LIKE LOWER('%rolls royce%') OR LOWER(name) LIKE LOWER('%bae systems%') OR LOWER(name) LIKE LOWER('%leonardo%') OR LOWER(name) LIKE LOWER('%thales%') OR LOWER(name) LIKE LOWER('%safran%')) OR (LOWER(operator) LIKE LOWER('%boeing%') OR LOWER(operator) LIKE LOWER('%airbus%') OR LOWER(operator) LIKE LOWER('%rolls royce%') OR LOWER(operator) LIKE LOWER('%bae systems%') OR LOWER(operator) LIKE LOWER('%leonardo%') OR LOWER(operator) LIKE LOWER('%thales%') OR LOWER(operator) LIKE LOWER('%safran%'))) THEN 50 ELSE 0 END +
        CASE WHEN ((LOWER(name) LIKE LOWER('%aerospace%') OR LOWER(name) LIKE LOWER('%aviation%') OR LOWER(name) LIKE LOWER('%aircraft%') OR LOWER(name) LIKE LOWER('%avionics%') OR LOWER(name) LIKE LOWER('%turbine%') OR LOWER(name) LIKE LOWER('%engine%')) OR (LOWER(operator) LIKE LOWER('%aerospace%') OR LOWER(operator) LIKE LOWER('%aviation%') OR LOWER(operator) LIKE LOWER('%aircraft%') OR LOWER(operator) LIKE LOWER('%avionics%') OR LOWER(operator) LIKE LOWER('%turbine%') OR LOWER(operator) LIKE LOWER('%engine%'))) THEN 30 ELSE 0 END +
        CASE WHEN ((LOWER(name) LIKE LOWER('%precision%') OR LOWER(name) LIKE LOWER('%machining%') OR LOWER(name) LIKE LOWER('%casting%') OR LOWER(name) LIKE LOWER('%forging%') OR LOWER(name) LIKE LOWER('%composite%') OR LOWER(name) LIKE LOWER('%materials%')) OR (LOWER(operator) LIKE LOWER('%precision%') OR LOWER(operator) LIKE LOWER('%machining%') OR LOWER(operator) LIKE LOWER('%casting%') OR LOWER(operator) LIKE LOWER('%forging%') OR LOWER(operator) LIKE LOWER('%composite%') OR LOWER(operator) LIKE LOWER('%materials%'))) THEN 20 ELSE 0 END +
        CASE WHEN (amenity IN ('restaurant', 'pub', 'cafe', 'bar', 'fast_food', 'fuel', 'hospital', 'school') OR shop IS NOT NULL OR tourism IS NOT NULL OR leisure IS NOT NULL OR building IN ('house', 'apartments', 'residential', 'hotel', 'retail')) THEN -50 ELSE 0 END +
        CASE WHEN (landuse IN ('residential', 'retail', 'commercial', 'farmland')) THEN -25 ELSE 0 END +
        CASE WHEN (office IN ('insurance', 'finance', 'estate_agent', 'lawyer', 'accountant') OR amenity IN ('bank', 'post_office', 'library')) THEN -15 ELSE 0 END
    ) AS aerospace_score,
    ARRAY[]::text[] AS matched_keywords,
    'planet_osm_polygon' AS source_table
FROM public.planet_osm_polygon_aerospace_filtered
WHERE (
    (
        CASE
        WHEN ((LOWER(name) LIKE LOWER('%aerospace%') OR LOWER(name) LIKE LOWER('%aviation%') OR LOWER(name) LIKE LOWER('%aircraft%') OR LOWER(name) LIKE LOWER('%airbus%') OR LOWER(name) LIKE LOWER('%boeing%') OR LOWER(name) LIKE LOWER('%bae%') OR LOWER(name) LIKE LOWER('%rolls royce%') OR LOWER(name) LIKE LOWER('%safran%') OR LOWER(name) LIKE LOWER('%leonardo%') OR LOWER(name) LIKE LOWER('%thales%')) OR (LOWER(operator) LIKE LOWER('%aerospace%') OR LOWER(operator) LIKE LOWER('%aviation%') OR LOWER(operator) LIKE LOWER('%aircraft%')) OR office IN ('aerospace', 'aviation')) THEN 100
        WHEN ((LOWER(name) LIKE LOWER('%defense%') OR LOWER(name) LIKE LOWER('%defence%') OR LOWER(name) LIKE LOWER('%military%') OR LOWER(name) LIKE LOWER('%radar%') OR LOWER(name) LIKE LOWER('%missile%') OR LOWER(name) LIKE LOWER('%weapons%')) OR military IS NOT NULL OR landuse IN ('military')) THEN 80
        WHEN ((LOWER(name) LIKE LOWER('%engineering%') OR LOWER(name) LIKE LOWER('%technology%') OR LOWER(name) LIKE LOWER('%systems%') OR LOWER(name) LIKE LOWER('%electronics%') OR LOWER(name) LIKE LOWER('%precision%') OR LOWER(name) LIKE LOWER('%advanced%')) OR industrial IN ('engineering', 'electronics', 'precision', 'high_tech') OR man_made IN ('works', 'factory') OR office IN ('engineering', 'research', 'technology') OR building IN ('industrial', 'factory', 'warehouse')) THEN 70
        WHEN (landuse IN ('industrial') OR building IN ('industrial', 'warehouse', 'manufacture') OR industrial IS NOT NULL) THEN 50
        WHEN ((LOWER(name) LIKE LOWER('%research%') OR LOWER(name) LIKE LOWER('%development%') OR LOWER(name) LIKE LOWER('%laboratory%') OR LOWER(name) LIKE LOWER('%institute%') OR LOWER(name) LIKE LOWER('%university%')) OR office IN ('research', 'engineering') OR amenity IN ('research_institute', 'university')) THEN 60
        ELSE 0
    END +
        CASE WHEN ((LOWER(name) LIKE LOWER('%boeing%') OR LOWER(name) LIKE LOWER('%airbus%') OR LOWER(name) LIKE LOWER('%rolls royce%') OR LOWER(name) LIKE LOWER('%bae systems%') OR LOWER(name) LIKE LOWER('%leonardo%') OR LOWER(name) LIKE LOWER('%thales%') OR LOWER(name) LIKE LOWER('%safran%')) OR (LOWER(operator) LIKE LOWER('%boeing%') OR LOWER(operator) LIKE LOWER('%airbus%') OR LOWER(operator) LIKE LOWER('%rolls royce%') OR LOWER(operator) LIKE LOWER('%bae systems%') OR LOWER(operator) LIKE LOWER('%leonardo%') OR LOWER(operator) LIKE LOWER('%thales%') OR LOWER(operator) LIKE LOWER('%safran%'))) THEN 50 ELSE 0 END +
        CASE WHEN ((LOWER(name) LIKE LOWER('%aerospace%') OR LOWER(name) LIKE LOWER('%aviation%') OR LOWER(name) LIKE LOWER('%aircraft%') OR LOWER(name) LIKE LOWER('%avionics%') OR LOWER(name) LIKE LOWER('%turbine%') OR LOWER(name) LIKE LOWER('%engine%')) OR (LOWER(operator) LIKE LOWER('%aerospace%') OR LOWER(operator) LIKE LOWER('%aviation%') OR LOWER(operator) LIKE LOWER('%aircraft%') OR LOWER(operator) LIKE LOWER('%avionics%') OR LOWER(operator) LIKE LOWER('%turbine%') OR LOWER(operator) LIKE LOWER('%engine%'))) THEN 30 ELSE 0 END +
        CASE WHEN ((LOWER(name) LIKE LOWER('%precision%') OR LOWER(name) LIKE LOWER('%machining%') OR LOWER(name) LIKE LOWER('%casting%') OR LOWER(name) LIKE LOWER('%forging%') OR LOWER(name) LIKE LOWER('%composite%') OR LOWER(name) LIKE LOWER('%materials%')) OR (LOWER(operator) LIKE LOWER('%precision%') OR LOWER(operator) LIKE LOWER('%machining%') OR LOWER(operator) LIKE LOWER('%casting%') OR LOWER(operator) LIKE LOWER('%forging%') OR LOWER(operator) LIKE LOWER('%composite%') OR LOWER(operator) LIKE LOWER('%materials%'))) THEN 20 ELSE 0 END +
        CASE WHEN (amenity IN ('restaurant', 'pub', 'cafe', 'bar', 'fast_food', 'fuel', 'hospital', 'school') OR shop IS NOT NULL OR tourism IS NOT NULL OR leisure IS NOT NULL OR building IN ('house', 'apartments', 'residential', 'hotel', 'retail')) THEN -50 ELSE 0 END +
        CASE WHEN (landuse IN ('residential', 'retail', 'commercial', 'farmland')) THEN -25 ELSE 0 END +
        CASE WHEN (office IN ('insurance', 'finance', 'estate_agent', 'lawyer', 'accountant') OR amenity IN ('bank', 'post_office', 'library')) THEN -15 ELSE 0 END
    )
) > 0;

-- Scored view for planet_osm_roads
CREATE OR REPLACE VIEW public.planet_osm_roads_aerospace_scored AS
SELECT *,
    (
        CASE
        WHEN ((LOWER(name) LIKE LOWER('%aerospace%') OR LOWER(name) LIKE LOWER('%aviation%') OR LOWER(name) LIKE LOWER('%aircraft%') OR LOWER(name) LIKE LOWER('%airbus%') OR LOWER(name) LIKE LOWER('%boeing%') OR LOWER(name) LIKE LOWER('%bae%') OR LOWER(name) LIKE LOWER('%rolls royce%') OR LOWER(name) LIKE LOWER('%safran%') OR LOWER(name) LIKE LOWER('%leonardo%') OR LOWER(name) LIKE LOWER('%thales%')) OR (LOWER(operator) LIKE LOWER('%aerospace%') OR LOWER(operator) LIKE LOWER('%aviation%') OR LOWER(operator) LIKE LOWER('%aircraft%')) OR office IN ('aerospace', 'aviation')) THEN 100
        WHEN ((LOWER(name) LIKE LOWER('%defense%') OR LOWER(name) LIKE LOWER('%defence%') OR LOWER(name) LIKE LOWER('%military%') OR LOWER(name) LIKE LOWER('%radar%') OR LOWER(name) LIKE LOWER('%missile%') OR LOWER(name) LIKE LOWER('%weapons%')) OR military IS NOT NULL OR landuse IN ('military')) THEN 80
        WHEN ((LOWER(name) LIKE LOWER('%engineering%') OR LOWER(name) LIKE LOWER('%technology%') OR LOWER(name) LIKE LOWER('%systems%') OR LOWER(name) LIKE LOWER('%electronics%') OR LOWER(name) LIKE LOWER('%precision%') OR LOWER(name) LIKE LOWER('%advanced%')) OR industrial IN ('engineering', 'electronics', 'precision', 'high_tech') OR man_made IN ('works', 'factory') OR office IN ('engineering', 'research', 'technology') OR building IN ('industrial', 'factory', 'warehouse')) THEN 70
        WHEN (landuse IN ('industrial') OR building IN ('industrial', 'warehouse', 'manufacture') OR industrial IS NOT NULL) THEN 50
        WHEN ((LOWER(name) LIKE LOWER('%research%') OR LOWER(name) LIKE LOWER('%development%') OR LOWER(name) LIKE LOWER('%laboratory%') OR LOWER(name) LIKE LOWER('%institute%') OR LOWER(name) LIKE LOWER('%university%')) OR office IN ('research', 'engineering') OR amenity IN ('research_institute', 'university')) THEN 60
        ELSE 0
    END +
        CASE WHEN ((LOWER(name) LIKE LOWER('%boeing%') OR LOWER(name) LIKE LOWER('%airbus%') OR LOWER(name) LIKE LOWER('%rolls royce%') OR LOWER(name) LIKE LOWER('%bae systems%') OR LOWER(name) LIKE LOWER('%leonardo%') OR LOWER(name) LIKE LOWER('%thales%') OR LOWER(name) LIKE LOWER('%safran%')) OR (LOWER(operator) LIKE LOWER('%boeing%') OR LOWER(operator) LIKE LOWER('%airbus%') OR LOWER(operator) LIKE LOWER('%rolls royce%') OR LOWER(operator) LIKE LOWER('%bae systems%') OR LOWER(operator) LIKE LOWER('%leonardo%') OR LOWER(operator) LIKE LOWER('%thales%') OR LOWER(operator) LIKE LOWER('%safran%'))) THEN 50 ELSE 0 END +
        CASE WHEN ((LOWER(name) LIKE LOWER('%aerospace%') OR LOWER(name) LIKE LOWER('%aviation%') OR LOWER(name) LIKE LOWER('%aircraft%') OR LOWER(name) LIKE LOWER('%avionics%') OR LOWER(name) LIKE LOWER('%turbine%') OR LOWER(name) LIKE LOWER('%engine%')) OR (LOWER(operator) LIKE LOWER('%aerospace%') OR LOWER(operator) LIKE LOWER('%aviation%') OR LOWER(operator) LIKE LOWER('%aircraft%') OR LOWER(operator) LIKE LOWER('%avionics%') OR LOWER(operator) LIKE LOWER('%turbine%') OR LOWER(operator) LIKE LOWER('%engine%'))) THEN 30 ELSE 0 END +
        CASE WHEN ((LOWER(name) LIKE LOWER('%precision%') OR LOWER(name) LIKE LOWER('%machining%') OR LOWER(name) LIKE LOWER('%casting%') OR LOWER(name) LIKE LOWER('%forging%') OR LOWER(name) LIKE LOWER('%composite%') OR LOWER(name) LIKE LOWER('%materials%')) OR (LOWER(operator) LIKE LOWER('%precision%') OR LOWER(operator) LIKE LOWER('%machining%') OR LOWER(operator) LIKE LOWER('%casting%') OR LOWER(operator) LIKE LOWER('%forging%') OR LOWER(operator) LIKE LOWER('%composite%') OR LOWER(operator) LIKE LOWER('%materials%'))) THEN 20 ELSE 0 END +
        CASE WHEN (amenity IN ('restaurant', 'pub', 'cafe', 'bar', 'fast_food', 'fuel', 'hospital', 'school') OR shop IS NOT NULL OR tourism IS NOT NULL OR leisure IS NOT NULL OR building IN ('house', 'apartments', 'residential', 'hotel', 'retail')) THEN -50 ELSE 0 END +
        CASE WHEN (landuse IN ('residential', 'retail', 'commercial', 'farmland')) THEN -25 ELSE 0 END +
        CASE WHEN (office IN ('insurance', 'finance', 'estate_agent', 'lawyer', 'accountant') OR amenity IN ('bank', 'post_office', 'library')) THEN -15 ELSE 0 END
    ) AS aerospace_score,
    ARRAY[]::text[] AS matched_keywords,
    'planet_osm_roads' AS source_table
FROM public.planet_osm_roads_aerospace_filtered
WHERE (
    (
        CASE
        WHEN ((LOWER(name) LIKE LOWER('%aerospace%') OR LOWER(name) LIKE LOWER('%aviation%') OR LOWER(name) LIKE LOWER('%aircraft%') OR LOWER(name) LIKE LOWER('%airbus%') OR LOWER(name) LIKE LOWER('%boeing%') OR LOWER(name) LIKE LOWER('%bae%') OR LOWER(name) LIKE LOWER('%rolls royce%') OR LOWER(name) LIKE LOWER('%safran%') OR LOWER(name) LIKE LOWER('%leonardo%') OR LOWER(name) LIKE LOWER('%thales%')) OR (LOWER(operator) LIKE LOWER('%aerospace%') OR LOWER(operator) LIKE LOWER('%aviation%') OR LOWER(operator) LIKE LOWER('%aircraft%')) OR office IN ('aerospace', 'aviation')) THEN 100
        WHEN ((LOWER(name) LIKE LOWER('%defense%') OR LOWER(name) LIKE LOWER('%defence%') OR LOWER(name) LIKE LOWER('%military%') OR LOWER(name) LIKE LOWER('%radar%') OR LOWER(name) LIKE LOWER('%missile%') OR LOWER(name) LIKE LOWER('%weapons%')) OR military IS NOT NULL OR landuse IN ('military')) THEN 80
        WHEN ((LOWER(name) LIKE LOWER('%engineering%') OR LOWER(name) LIKE LOWER('%technology%') OR LOWER(name) LIKE LOWER('%systems%') OR LOWER(name) LIKE LOWER('%electronics%') OR LOWER(name) LIKE LOWER('%precision%') OR LOWER(name) LIKE LOWER('%advanced%')) OR industrial IN ('engineering', 'electronics', 'precision', 'high_tech') OR man_made IN ('works', 'factory') OR office IN ('engineering', 'research', 'technology') OR building IN ('industrial', 'factory', 'warehouse')) THEN 70
        WHEN (landuse IN ('industrial') OR building IN ('industrial', 'warehouse', 'manufacture') OR industrial IS NOT NULL) THEN 50
        WHEN ((LOWER(name) LIKE LOWER('%research%') OR LOWER(name) LIKE LOWER('%development%') OR LOWER(name) LIKE LOWER('%laboratory%') OR LOWER(name) LIKE LOWER('%institute%') OR LOWER(name) LIKE LOWER('%university%')) OR office IN ('research', 'engineering') OR amenity IN ('research_institute', 'university')) THEN 60
        ELSE 0
    END +
        CASE WHEN ((LOWER(name) LIKE LOWER('%boeing%') OR LOWER(name) LIKE LOWER('%airbus%') OR LOWER(name) LIKE LOWER('%rolls royce%') OR LOWER(name) LIKE LOWER('%bae systems%') OR LOWER(name) LIKE LOWER('%leonardo%') OR LOWER(name) LIKE LOWER('%thales%') OR LOWER(name) LIKE LOWER('%safran%')) OR (LOWER(operator) LIKE LOWER('%boeing%') OR LOWER(operator) LIKE LOWER('%airbus%') OR LOWER(operator) LIKE LOWER('%rolls royce%') OR LOWER(operator) LIKE LOWER('%bae systems%') OR LOWER(operator) LIKE LOWER('%leonardo%') OR LOWER(operator) LIKE LOWER('%thales%') OR LOWER(operator) LIKE LOWER('%safran%'))) THEN 50 ELSE 0 END +
        CASE WHEN ((LOWER(name) LIKE LOWER('%aerospace%') OR LOWER(name) LIKE LOWER('%aviation%') OR LOWER(name) LIKE LOWER('%aircraft%') OR LOWER(name) LIKE LOWER('%avionics%') OR LOWER(name) LIKE LOWER('%turbine%') OR LOWER(name) LIKE LOWER('%engine%')) OR (LOWER(operator) LIKE LOWER('%aerospace%') OR LOWER(operator) LIKE LOWER('%aviation%') OR LOWER(operator) LIKE LOWER('%aircraft%') OR LOWER(operator) LIKE LOWER('%avionics%') OR LOWER(operator) LIKE LOWER('%turbine%') OR LOWER(operator) LIKE LOWER('%engine%'))) THEN 30 ELSE 0 END +
        CASE WHEN ((LOWER(name) LIKE LOWER('%precision%') OR LOWER(name) LIKE LOWER('%machining%') OR LOWER(name) LIKE LOWER('%casting%') OR LOWER(name) LIKE LOWER('%forging%') OR LOWER(name) LIKE LOWER('%composite%') OR LOWER(name) LIKE LOWER('%materials%')) OR (LOWER(operator) LIKE LOWER('%precision%') OR LOWER(operator) LIKE LOWER('%machining%') OR LOWER(operator) LIKE LOWER('%casting%') OR LOWER(operator) LIKE LOWER('%forging%') OR LOWER(operator) LIKE LOWER('%composite%') OR LOWER(operator) LIKE LOWER('%materials%'))) THEN 20 ELSE 0 END +
        CASE WHEN (amenity IN ('restaurant', 'pub', 'cafe', 'bar', 'fast_food', 'fuel', 'hospital', 'school') OR shop IS NOT NULL OR tourism IS NOT NULL OR leisure IS NOT NULL OR building IN ('house', 'apartments', 'residential', 'hotel', 'retail')) THEN -50 ELSE 0 END +
        CASE WHEN (landuse IN ('residential', 'retail', 'commercial', 'farmland')) THEN -25 ELSE 0 END +
        CASE WHEN (office IN ('insurance', 'finance', 'estate_agent', 'lawyer', 'accountant') OR amenity IN ('bank', 'post_office', 'library')) THEN -15 ELSE 0 END
    )
) > 0;
