-- Aerospace Supplier Scoring SQL
-- Generated: 2025-10-01T08:12:44.397856
-- Schema: public

-- Scored view for planet_osm_point
CREATE OR REPLACE VIEW public.planet_osm_point_aerospace_scored AS
SELECT
  source.*,
  (
    CASE
    WHEN ((LOWER(source."name") LIKE LOWER('%aerospace%') OR LOWER(source."name") LIKE LOWER('%aviation%') OR LOWER(source."name") LIKE LOWER('%aircraft%') OR LOWER(source."name") LIKE LOWER('%airbus%') OR LOWER(source."name") LIKE LOWER('%boeing%') OR LOWER(source."name") LIKE LOWER('%bae%') OR LOWER(source."name") LIKE LOWER('%rolls royce%') OR LOWER(source."name") LIKE LOWER('%safran%') OR LOWER(source."name") LIKE LOWER('%leonardo%') OR LOWER(source."name") LIKE LOWER('%thales%')) OR (LOWER(source."operator") LIKE LOWER('%aerospace%') OR LOWER(source."operator") LIKE LOWER('%aviation%') OR LOWER(source."operator") LIKE LOWER('%aircraft%')) OR source."office" IN ('aerospace','aviation')) THEN 100
    WHEN ((LOWER(source."name") LIKE LOWER('%defense%') OR LOWER(source."name") LIKE LOWER('%defence%') OR LOWER(source."name") LIKE LOWER('%military%') OR LOWER(source."name") LIKE LOWER('%radar%') OR LOWER(source."name") LIKE LOWER('%missile%') OR LOWER(source."name") LIKE LOWER('%weapons%')) OR source."military" IS NOT NULL OR source."landuse" IN ('military')) THEN 80
    WHEN ((LOWER(source."name") LIKE LOWER('%engineering%') OR LOWER(source."name") LIKE LOWER('%technology%') OR LOWER(source."name") LIKE LOWER('%systems%') OR LOWER(source."name") LIKE LOWER('%electronics%') OR LOWER(source."name") LIKE LOWER('%precision%') OR LOWER(source."name") LIKE LOWER('%advanced%')) OR source."man_made" IN ('works','factory') OR source."office" IN ('engineering','research','technology')) THEN 70
    WHEN (source."landuse" IN ('industrial')) THEN 50
    WHEN ((LOWER(source."name") LIKE LOWER('%research%') OR LOWER(source."name") LIKE LOWER('%development%') OR LOWER(source."name") LIKE LOWER('%laboratory%') OR LOWER(source."name") LIKE LOWER('%institute%') OR LOWER(source."name") LIKE LOWER('%university%')) OR source."office" IN ('research','engineering') OR source."amenity" IN ('research_institute','university')) THEN 60
    ELSE 0
END +
    CASE WHEN ((LOWER(source."name") LIKE LOWER('%boeing%') OR LOWER(source."name") LIKE LOWER('%airbus%') OR LOWER(source."name") LIKE LOWER('%rolls royce%') OR LOWER(source."name") LIKE LOWER('%bae systems%') OR LOWER(source."name") LIKE LOWER('%leonardo%') OR LOWER(source."name") LIKE LOWER('%thales%') OR LOWER(source."name") LIKE LOWER('%safran%')) OR (LOWER(source."operator") LIKE LOWER('%boeing%') OR LOWER(source."operator") LIKE LOWER('%airbus%') OR LOWER(source."operator") LIKE LOWER('%rolls royce%') OR LOWER(source."operator") LIKE LOWER('%bae systems%') OR LOWER(source."operator") LIKE LOWER('%leonardo%') OR LOWER(source."operator") LIKE LOWER('%thales%') OR LOWER(source."operator") LIKE LOWER('%safran%'))) THEN 50 ELSE 0 END +
    CASE WHEN ((LOWER(source."name") LIKE LOWER('%aerospace%') OR LOWER(source."name") LIKE LOWER('%aviation%') OR LOWER(source."name") LIKE LOWER('%aircraft%') OR LOWER(source."name") LIKE LOWER('%avionics%') OR LOWER(source."name") LIKE LOWER('%turbine%') OR LOWER(source."name") LIKE LOWER('%engine%')) OR (LOWER(source."operator") LIKE LOWER('%aerospace%') OR LOWER(source."operator") LIKE LOWER('%aviation%') OR LOWER(source."operator") LIKE LOWER('%aircraft%') OR LOWER(source."operator") LIKE LOWER('%avionics%') OR LOWER(source."operator") LIKE LOWER('%turbine%') OR LOWER(source."operator") LIKE LOWER('%engine%'))) THEN 30 ELSE 0 END +
    CASE WHEN ((LOWER(source."name") LIKE LOWER('%precision%') OR LOWER(source."name") LIKE LOWER('%machining%') OR LOWER(source."name") LIKE LOWER('%casting%') OR LOWER(source."name") LIKE LOWER('%forging%') OR LOWER(source."name") LIKE LOWER('%composite%') OR LOWER(source."name") LIKE LOWER('%materials%')) OR (LOWER(source."operator") LIKE LOWER('%precision%') OR LOWER(source."operator") LIKE LOWER('%machining%') OR LOWER(source."operator") LIKE LOWER('%casting%') OR LOWER(source."operator") LIKE LOWER('%forging%') OR LOWER(source."operator") LIKE LOWER('%composite%') OR LOWER(source."operator") LIKE LOWER('%materials%'))) THEN 20 ELSE 0 END +
    CASE WHEN (source."amenity" IN ('restaurant','pub','cafe','bar','fast_food','fuel','hospital','school') OR source."shop" IS NOT NULL OR source."tourism" IS NOT NULL OR source."leisure" IS NOT NULL) THEN -50 ELSE 0 END +
    CASE WHEN (source."landuse" IN ('residential','retail','commercial','farmland')) THEN -25 ELSE 0 END +
    CASE WHEN (source."office" IN ('insurance','finance','estate_agent','lawyer','accountant') OR source."amenity" IN ('bank','post_office','library')) THEN -15 ELSE 0 END
) AS aerospace_score,
  ARRAY[]::text[] AS matched_keywords,
  'planet_osm_point' AS source_table
FROM public.planet_osm_point_aerospace_filtered filtered
JOIN public.planet_osm_point source ON filtered.osm_id = source.osm_id
WHERE
  (
    CASE
    WHEN ((LOWER(source."name") LIKE LOWER('%aerospace%') OR LOWER(source."name") LIKE LOWER('%aviation%') OR LOWER(source."name") LIKE LOWER('%aircraft%') OR LOWER(source."name") LIKE LOWER('%airbus%') OR LOWER(source."name") LIKE LOWER('%boeing%') OR LOWER(source."name") LIKE LOWER('%bae%') OR LOWER(source."name") LIKE LOWER('%rolls royce%') OR LOWER(source."name") LIKE LOWER('%safran%') OR LOWER(source."name") LIKE LOWER('%leonardo%') OR LOWER(source."name") LIKE LOWER('%thales%')) OR (LOWER(source."operator") LIKE LOWER('%aerospace%') OR LOWER(source."operator") LIKE LOWER('%aviation%') OR LOWER(source."operator") LIKE LOWER('%aircraft%')) OR source."office" IN ('aerospace','aviation')) THEN 100
    WHEN ((LOWER(source."name") LIKE LOWER('%defense%') OR LOWER(source."name") LIKE LOWER('%defence%') OR LOWER(source."name") LIKE LOWER('%military%') OR LOWER(source."name") LIKE LOWER('%radar%') OR LOWER(source."name") LIKE LOWER('%missile%') OR LOWER(source."name") LIKE LOWER('%weapons%')) OR source."military" IS NOT NULL OR source."landuse" IN ('military')) THEN 80
    WHEN ((LOWER(source."name") LIKE LOWER('%engineering%') OR LOWER(source."name") LIKE LOWER('%technology%') OR LOWER(source."name") LIKE LOWER('%systems%') OR LOWER(source."name") LIKE LOWER('%electronics%') OR LOWER(source."name") LIKE LOWER('%precision%') OR LOWER(source."name") LIKE LOWER('%advanced%')) OR source."man_made" IN ('works','factory') OR source."office" IN ('engineering','research','technology')) THEN 70
    WHEN (source."landuse" IN ('industrial')) THEN 50
    WHEN ((LOWER(source."name") LIKE LOWER('%research%') OR LOWER(source."name") LIKE LOWER('%development%') OR LOWER(source."name") LIKE LOWER('%laboratory%') OR LOWER(source."name") LIKE LOWER('%institute%') OR LOWER(source."name") LIKE LOWER('%university%')) OR source."office" IN ('research','engineering') OR source."amenity" IN ('research_institute','university')) THEN 60
    ELSE 0
END +
    CASE WHEN ((LOWER(source."name") LIKE LOWER('%boeing%') OR LOWER(source."name") LIKE LOWER('%airbus%') OR LOWER(source."name") LIKE LOWER('%rolls royce%') OR LOWER(source."name") LIKE LOWER('%bae systems%') OR LOWER(source."name") LIKE LOWER('%leonardo%') OR LOWER(source."name") LIKE LOWER('%thales%') OR LOWER(source."name") LIKE LOWER('%safran%')) OR (LOWER(source."operator") LIKE LOWER('%boeing%') OR LOWER(source."operator") LIKE LOWER('%airbus%') OR LOWER(source."operator") LIKE LOWER('%rolls royce%') OR LOWER(source."operator") LIKE LOWER('%bae systems%') OR LOWER(source."operator") LIKE LOWER('%leonardo%') OR LOWER(source."operator") LIKE LOWER('%thales%') OR LOWER(source."operator") LIKE LOWER('%safran%'))) THEN 50 ELSE 0 END +
    CASE WHEN ((LOWER(source."name") LIKE LOWER('%aerospace%') OR LOWER(source."name") LIKE LOWER('%aviation%') OR LOWER(source."name") LIKE LOWER('%aircraft%') OR LOWER(source."name") LIKE LOWER('%avionics%') OR LOWER(source."name") LIKE LOWER('%turbine%') OR LOWER(source."name") LIKE LOWER('%engine%')) OR (LOWER(source."operator") LIKE LOWER('%aerospace%') OR LOWER(source."operator") LIKE LOWER('%aviation%') OR LOWER(source."operator") LIKE LOWER('%aircraft%') OR LOWER(source."operator") LIKE LOWER('%avionics%') OR LOWER(source."operator") LIKE LOWER('%turbine%') OR LOWER(source."operator") LIKE LOWER('%engine%'))) THEN 30 ELSE 0 END +
    CASE WHEN ((LOWER(source."name") LIKE LOWER('%precision%') OR LOWER(source."name") LIKE LOWER('%machining%') OR LOWER(source."name") LIKE LOWER('%casting%') OR LOWER(source."name") LIKE LOWER('%forging%') OR LOWER(source."name") LIKE LOWER('%composite%') OR LOWER(source."name") LIKE LOWER('%materials%')) OR (LOWER(source."operator") LIKE LOWER('%precision%') OR LOWER(source."operator") LIKE LOWER('%machining%') OR LOWER(source."operator") LIKE LOWER('%casting%') OR LOWER(source."operator") LIKE LOWER('%forging%') OR LOWER(source."operator") LIKE LOWER('%composite%') OR LOWER(source."operator") LIKE LOWER('%materials%'))) THEN 20 ELSE 0 END +
    CASE WHEN (source."amenity" IN ('restaurant','pub','cafe','bar','fast_food','fuel','hospital','school') OR source."shop" IS NOT NULL OR source."tourism" IS NOT NULL OR source."leisure" IS NOT NULL) THEN -50 ELSE 0 END +
    CASE WHEN (source."landuse" IN ('residential','retail','commercial','farmland')) THEN -25 ELSE 0 END +
    CASE WHEN (source."office" IN ('insurance','finance','estate_agent','lawyer','accountant') OR source."amenity" IN ('bank','post_office','library')) THEN -15 ELSE 0 END
) > 0;

-- Scored view for planet_osm_line
CREATE OR REPLACE VIEW public.planet_osm_line_aerospace_scored AS
SELECT
  source.*,
  (
    CASE
    WHEN ((LOWER(source."name") LIKE LOWER('%aerospace%') OR LOWER(source."name") LIKE LOWER('%aviation%') OR LOWER(source."name") LIKE LOWER('%aircraft%') OR LOWER(source."name") LIKE LOWER('%airbus%') OR LOWER(source."name") LIKE LOWER('%boeing%') OR LOWER(source."name") LIKE LOWER('%bae%') OR LOWER(source."name") LIKE LOWER('%rolls royce%') OR LOWER(source."name") LIKE LOWER('%safran%') OR LOWER(source."name") LIKE LOWER('%leonardo%') OR LOWER(source."name") LIKE LOWER('%thales%')) OR (LOWER(source."operator") LIKE LOWER('%aerospace%') OR LOWER(source."operator") LIKE LOWER('%aviation%') OR LOWER(source."operator") LIKE LOWER('%aircraft%')) OR source."office" IN ('aerospace','aviation')) THEN 100
    WHEN ((LOWER(source."name") LIKE LOWER('%defense%') OR LOWER(source."name") LIKE LOWER('%defence%') OR LOWER(source."name") LIKE LOWER('%military%') OR LOWER(source."name") LIKE LOWER('%radar%') OR LOWER(source."name") LIKE LOWER('%missile%') OR LOWER(source."name") LIKE LOWER('%weapons%')) OR source."military" IS NOT NULL OR source."landuse" IN ('military')) THEN 80
    WHEN ((LOWER(source."name") LIKE LOWER('%engineering%') OR LOWER(source."name") LIKE LOWER('%technology%') OR LOWER(source."name") LIKE LOWER('%systems%') OR LOWER(source."name") LIKE LOWER('%electronics%') OR LOWER(source."name") LIKE LOWER('%precision%') OR LOWER(source."name") LIKE LOWER('%advanced%')) OR source."industrial" IN ('engineering','electronics','precision','high_tech') OR source."man_made" IN ('works','factory') OR source."office" IN ('engineering','research','technology') OR source."building" IN ('industrial','factory','warehouse')) THEN 70
    WHEN (source."landuse" IN ('industrial') OR source."building" IN ('industrial','warehouse','manufacture') OR source."industrial" IS NOT NULL) THEN 50
    WHEN ((LOWER(source."name") LIKE LOWER('%research%') OR LOWER(source."name") LIKE LOWER('%development%') OR LOWER(source."name") LIKE LOWER('%laboratory%') OR LOWER(source."name") LIKE LOWER('%institute%') OR LOWER(source."name") LIKE LOWER('%university%')) OR source."office" IN ('research','engineering') OR source."amenity" IN ('research_institute','university')) THEN 60
    ELSE 0
END +
    CASE WHEN ((LOWER(source."name") LIKE LOWER('%boeing%') OR LOWER(source."name") LIKE LOWER('%airbus%') OR LOWER(source."name") LIKE LOWER('%rolls royce%') OR LOWER(source."name") LIKE LOWER('%bae systems%') OR LOWER(source."name") LIKE LOWER('%leonardo%') OR LOWER(source."name") LIKE LOWER('%thales%') OR LOWER(source."name") LIKE LOWER('%safran%')) OR (LOWER(source."operator") LIKE LOWER('%boeing%') OR LOWER(source."operator") LIKE LOWER('%airbus%') OR LOWER(source."operator") LIKE LOWER('%rolls royce%') OR LOWER(source."operator") LIKE LOWER('%bae systems%') OR LOWER(source."operator") LIKE LOWER('%leonardo%') OR LOWER(source."operator") LIKE LOWER('%thales%') OR LOWER(source."operator") LIKE LOWER('%safran%'))) THEN 50 ELSE 0 END +
    CASE WHEN ((LOWER(source."name") LIKE LOWER('%aerospace%') OR LOWER(source."name") LIKE LOWER('%aviation%') OR LOWER(source."name") LIKE LOWER('%aircraft%') OR LOWER(source."name") LIKE LOWER('%avionics%') OR LOWER(source."name") LIKE LOWER('%turbine%') OR LOWER(source."name") LIKE LOWER('%engine%')) OR (LOWER(source."operator") LIKE LOWER('%aerospace%') OR LOWER(source."operator") LIKE LOWER('%aviation%') OR LOWER(source."operator") LIKE LOWER('%aircraft%') OR LOWER(source."operator") LIKE LOWER('%avionics%') OR LOWER(source."operator") LIKE LOWER('%turbine%') OR LOWER(source."operator") LIKE LOWER('%engine%'))) THEN 30 ELSE 0 END +
    CASE WHEN ((LOWER(source."name") LIKE LOWER('%precision%') OR LOWER(source."name") LIKE LOWER('%machining%') OR LOWER(source."name") LIKE LOWER('%casting%') OR LOWER(source."name") LIKE LOWER('%forging%') OR LOWER(source."name") LIKE LOWER('%composite%') OR LOWER(source."name") LIKE LOWER('%materials%')) OR (LOWER(source."operator") LIKE LOWER('%precision%') OR LOWER(source."operator") LIKE LOWER('%machining%') OR LOWER(source."operator") LIKE LOWER('%casting%') OR LOWER(source."operator") LIKE LOWER('%forging%') OR LOWER(source."operator") LIKE LOWER('%composite%') OR LOWER(source."operator") LIKE LOWER('%materials%'))) THEN 20 ELSE 0 END +
    CASE WHEN (source."amenity" IN ('restaurant','pub','cafe','bar','fast_food','fuel','hospital','school') OR source."shop" IS NOT NULL OR source."tourism" IS NOT NULL OR source."leisure" IS NOT NULL OR source."building" IN ('house','apartments','residential','hotel','retail')) THEN -50 ELSE 0 END +
    CASE WHEN (source."landuse" IN ('residential','retail','commercial','farmland')) THEN -25 ELSE 0 END +
    CASE WHEN (source."office" IN ('insurance','finance','estate_agent','lawyer','accountant') OR source."amenity" IN ('bank','post_office','library')) THEN -15 ELSE 0 END
) AS aerospace_score,
  ARRAY[]::text[] AS matched_keywords,
  'planet_osm_line' AS source_table
FROM public.planet_osm_line_aerospace_filtered filtered
JOIN public.planet_osm_line source ON filtered.osm_id = source.osm_id
WHERE
  (
    CASE
    WHEN ((LOWER(source."name") LIKE LOWER('%aerospace%') OR LOWER(source."name") LIKE LOWER('%aviation%') OR LOWER(source."name") LIKE LOWER('%aircraft%') OR LOWER(source."name") LIKE LOWER('%airbus%') OR LOWER(source."name") LIKE LOWER('%boeing%') OR LOWER(source."name") LIKE LOWER('%bae%') OR LOWER(source."name") LIKE LOWER('%rolls royce%') OR LOWER(source."name") LIKE LOWER('%safran%') OR LOWER(source."name") LIKE LOWER('%leonardo%') OR LOWER(source."name") LIKE LOWER('%thales%')) OR (LOWER(source."operator") LIKE LOWER('%aerospace%') OR LOWER(source."operator") LIKE LOWER('%aviation%') OR LOWER(source."operator") LIKE LOWER('%aircraft%')) OR source."office" IN ('aerospace','aviation')) THEN 100
    WHEN ((LOWER(source."name") LIKE LOWER('%defense%') OR LOWER(source."name") LIKE LOWER('%defence%') OR LOWER(source."name") LIKE LOWER('%military%') OR LOWER(source."name") LIKE LOWER('%radar%') OR LOWER(source."name") LIKE LOWER('%missile%') OR LOWER(source."name") LIKE LOWER('%weapons%')) OR source."military" IS NOT NULL OR source."landuse" IN ('military')) THEN 80
    WHEN ((LOWER(source."name") LIKE LOWER('%engineering%') OR LOWER(source."name") LIKE LOWER('%technology%') OR LOWER(source."name") LIKE LOWER('%systems%') OR LOWER(source."name") LIKE LOWER('%electronics%') OR LOWER(source."name") LIKE LOWER('%precision%') OR LOWER(source."name") LIKE LOWER('%advanced%')) OR source."industrial" IN ('engineering','electronics','precision','high_tech') OR source."man_made" IN ('works','factory') OR source."office" IN ('engineering','research','technology') OR source."building" IN ('industrial','factory','warehouse')) THEN 70
    WHEN (source."landuse" IN ('industrial') OR source."building" IN ('industrial','warehouse','manufacture') OR source."industrial" IS NOT NULL) THEN 50
    WHEN ((LOWER(source."name") LIKE LOWER('%research%') OR LOWER(source."name") LIKE LOWER('%development%') OR LOWER(source."name") LIKE LOWER('%laboratory%') OR LOWER(source."name") LIKE LOWER('%institute%') OR LOWER(source."name") LIKE LOWER('%university%')) OR source."office" IN ('research','engineering') OR source."amenity" IN ('research_institute','university')) THEN 60
    ELSE 0
END +
    CASE WHEN ((LOWER(source."name") LIKE LOWER('%boeing%') OR LOWER(source."name") LIKE LOWER('%airbus%') OR LOWER(source."name") LIKE LOWER('%rolls royce%') OR LOWER(source."name") LIKE LOWER('%bae systems%') OR LOWER(source."name") LIKE LOWER('%leonardo%') OR LOWER(source."name") LIKE LOWER('%thales%') OR LOWER(source."name") LIKE LOWER('%safran%')) OR (LOWER(source."operator") LIKE LOWER('%boeing%') OR LOWER(source."operator") LIKE LOWER('%airbus%') OR LOWER(source."operator") LIKE LOWER('%rolls royce%') OR LOWER(source."operator") LIKE LOWER('%bae systems%') OR LOWER(source."operator") LIKE LOWER('%leonardo%') OR LOWER(source."operator") LIKE LOWER('%thales%') OR LOWER(source."operator") LIKE LOWER('%safran%'))) THEN 50 ELSE 0 END +
    CASE WHEN ((LOWER(source."name") LIKE LOWER('%aerospace%') OR LOWER(source."name") LIKE LOWER('%aviation%') OR LOWER(source."name") LIKE LOWER('%aircraft%') OR LOWER(source."name") LIKE LOWER('%avionics%') OR LOWER(source."name") LIKE LOWER('%turbine%') OR LOWER(source."name") LIKE LOWER('%engine%')) OR (LOWER(source."operator") LIKE LOWER('%aerospace%') OR LOWER(source."operator") LIKE LOWER('%aviation%') OR LOWER(source."operator") LIKE LOWER('%aircraft%') OR LOWER(source."operator") LIKE LOWER('%avionics%') OR LOWER(source."operator") LIKE LOWER('%turbine%') OR LOWER(source."operator") LIKE LOWER('%engine%'))) THEN 30 ELSE 0 END +
    CASE WHEN ((LOWER(source."name") LIKE LOWER('%precision%') OR LOWER(source."name") LIKE LOWER('%machining%') OR LOWER(source."name") LIKE LOWER('%casting%') OR LOWER(source."name") LIKE LOWER('%forging%') OR LOWER(source."name") LIKE LOWER('%composite%') OR LOWER(source."name") LIKE LOWER('%materials%')) OR (LOWER(source."operator") LIKE LOWER('%precision%') OR LOWER(source."operator") LIKE LOWER('%machining%') OR LOWER(source."operator") LIKE LOWER('%casting%') OR LOWER(source."operator") LIKE LOWER('%forging%') OR LOWER(source."operator") LIKE LOWER('%composite%') OR LOWER(source."operator") LIKE LOWER('%materials%'))) THEN 20 ELSE 0 END +
    CASE WHEN (source."amenity" IN ('restaurant','pub','cafe','bar','fast_food','fuel','hospital','school') OR source."shop" IS NOT NULL OR source."tourism" IS NOT NULL OR source."leisure" IS NOT NULL OR source."building" IN ('house','apartments','residential','hotel','retail')) THEN -50 ELSE 0 END +
    CASE WHEN (source."landuse" IN ('residential','retail','commercial','farmland')) THEN -25 ELSE 0 END +
    CASE WHEN (source."office" IN ('insurance','finance','estate_agent','lawyer','accountant') OR source."amenity" IN ('bank','post_office','library')) THEN -15 ELSE 0 END
) > 0;

-- Scored view for planet_osm_polygon
CREATE OR REPLACE VIEW public.planet_osm_polygon_aerospace_scored AS
SELECT
  source.*,
  (
    CASE
    WHEN ((LOWER(source."name") LIKE LOWER('%aerospace%') OR LOWER(source."name") LIKE LOWER('%aviation%') OR LOWER(source."name") LIKE LOWER('%aircraft%') OR LOWER(source."name") LIKE LOWER('%airbus%') OR LOWER(source."name") LIKE LOWER('%boeing%') OR LOWER(source."name") LIKE LOWER('%bae%') OR LOWER(source."name") LIKE LOWER('%rolls royce%') OR LOWER(source."name") LIKE LOWER('%safran%') OR LOWER(source."name") LIKE LOWER('%leonardo%') OR LOWER(source."name") LIKE LOWER('%thales%')) OR (LOWER(source."operator") LIKE LOWER('%aerospace%') OR LOWER(source."operator") LIKE LOWER('%aviation%') OR LOWER(source."operator") LIKE LOWER('%aircraft%')) OR source."office" IN ('aerospace','aviation')) THEN 100
    WHEN ((LOWER(source."name") LIKE LOWER('%defense%') OR LOWER(source."name") LIKE LOWER('%defence%') OR LOWER(source."name") LIKE LOWER('%military%') OR LOWER(source."name") LIKE LOWER('%radar%') OR LOWER(source."name") LIKE LOWER('%missile%') OR LOWER(source."name") LIKE LOWER('%weapons%')) OR source."military" IS NOT NULL OR source."landuse" IN ('military')) THEN 80
    WHEN ((LOWER(source."name") LIKE LOWER('%engineering%') OR LOWER(source."name") LIKE LOWER('%technology%') OR LOWER(source."name") LIKE LOWER('%systems%') OR LOWER(source."name") LIKE LOWER('%electronics%') OR LOWER(source."name") LIKE LOWER('%precision%') OR LOWER(source."name") LIKE LOWER('%advanced%')) OR source."industrial" IN ('engineering','electronics','precision','high_tech') OR source."man_made" IN ('works','factory') OR source."office" IN ('engineering','research','technology') OR source."building" IN ('industrial','factory','warehouse')) THEN 70
    WHEN (source."landuse" IN ('industrial') OR source."building" IN ('industrial','warehouse','manufacture') OR source."industrial" IS NOT NULL) THEN 50
    WHEN ((LOWER(source."name") LIKE LOWER('%research%') OR LOWER(source."name") LIKE LOWER('%development%') OR LOWER(source."name") LIKE LOWER('%laboratory%') OR LOWER(source."name") LIKE LOWER('%institute%') OR LOWER(source."name") LIKE LOWER('%university%')) OR source."office" IN ('research','engineering') OR source."amenity" IN ('research_institute','university')) THEN 60
    ELSE 0
END +
    CASE WHEN ((LOWER(source."name") LIKE LOWER('%boeing%') OR LOWER(source."name") LIKE LOWER('%airbus%') OR LOWER(source."name") LIKE LOWER('%rolls royce%') OR LOWER(source."name") LIKE LOWER('%bae systems%') OR LOWER(source."name") LIKE LOWER('%leonardo%') OR LOWER(source."name") LIKE LOWER('%thales%') OR LOWER(source."name") LIKE LOWER('%safran%')) OR (LOWER(source."operator") LIKE LOWER('%boeing%') OR LOWER(source."operator") LIKE LOWER('%airbus%') OR LOWER(source."operator") LIKE LOWER('%rolls royce%') OR LOWER(source."operator") LIKE LOWER('%bae systems%') OR LOWER(source."operator") LIKE LOWER('%leonardo%') OR LOWER(source."operator") LIKE LOWER('%thales%') OR LOWER(source."operator") LIKE LOWER('%safran%'))) THEN 50 ELSE 0 END +
    CASE WHEN ((LOWER(source."name") LIKE LOWER('%aerospace%') OR LOWER(source."name") LIKE LOWER('%aviation%') OR LOWER(source."name") LIKE LOWER('%aircraft%') OR LOWER(source."name") LIKE LOWER('%avionics%') OR LOWER(source."name") LIKE LOWER('%turbine%') OR LOWER(source."name") LIKE LOWER('%engine%')) OR (LOWER(source."operator") LIKE LOWER('%aerospace%') OR LOWER(source."operator") LIKE LOWER('%aviation%') OR LOWER(source."operator") LIKE LOWER('%aircraft%') OR LOWER(source."operator") LIKE LOWER('%avionics%') OR LOWER(source."operator") LIKE LOWER('%turbine%') OR LOWER(source."operator") LIKE LOWER('%engine%'))) THEN 30 ELSE 0 END +
    CASE WHEN ((LOWER(source."name") LIKE LOWER('%precision%') OR LOWER(source."name") LIKE LOWER('%machining%') OR LOWER(source."name") LIKE LOWER('%casting%') OR LOWER(source."name") LIKE LOWER('%forging%') OR LOWER(source."name") LIKE LOWER('%composite%') OR LOWER(source."name") LIKE LOWER('%materials%')) OR (LOWER(source."operator") LIKE LOWER('%precision%') OR LOWER(source."operator") LIKE LOWER('%machining%') OR LOWER(source."operator") LIKE LOWER('%casting%') OR LOWER(source."operator") LIKE LOWER('%forging%') OR LOWER(source."operator") LIKE LOWER('%composite%') OR LOWER(source."operator") LIKE LOWER('%materials%'))) THEN 20 ELSE 0 END +
    CASE WHEN (source."amenity" IN ('restaurant','pub','cafe','bar','fast_food','fuel','hospital','school') OR source."shop" IS NOT NULL OR source."tourism" IS NOT NULL OR source."leisure" IS NOT NULL OR source."building" IN ('house','apartments','residential','hotel','retail')) THEN -50 ELSE 0 END +
    CASE WHEN (source."landuse" IN ('residential','retail','commercial','farmland')) THEN -25 ELSE 0 END +
    CASE WHEN (source."office" IN ('insurance','finance','estate_agent','lawyer','accountant') OR source."amenity" IN ('bank','post_office','library')) THEN -15 ELSE 0 END
) AS aerospace_score,
  ARRAY[]::text[] AS matched_keywords,
  'planet_osm_polygon' AS source_table
FROM public.planet_osm_polygon_aerospace_filtered filtered
JOIN public.planet_osm_polygon source ON filtered.osm_id = source.osm_id
WHERE
  (
    CASE
    WHEN ((LOWER(source."name") LIKE LOWER('%aerospace%') OR LOWER(source."name") LIKE LOWER('%aviation%') OR LOWER(source."name") LIKE LOWER('%aircraft%') OR LOWER(source."name") LIKE LOWER('%airbus%') OR LOWER(source."name") LIKE LOWER('%boeing%') OR LOWER(source."name") LIKE LOWER('%bae%') OR LOWER(source."name") LIKE LOWER('%rolls royce%') OR LOWER(source."name") LIKE LOWER('%safran%') OR LOWER(source."name") LIKE LOWER('%leonardo%') OR LOWER(source."name") LIKE LOWER('%thales%')) OR (LOWER(source."operator") LIKE LOWER('%aerospace%') OR LOWER(source."operator") LIKE LOWER('%aviation%') OR LOWER(source."operator") LIKE LOWER('%aircraft%')) OR source."office" IN ('aerospace','aviation')) THEN 100
    WHEN ((LOWER(source."name") LIKE LOWER('%defense%') OR LOWER(source."name") LIKE LOWER('%defence%') OR LOWER(source."name") LIKE LOWER('%military%') OR LOWER(source."name") LIKE LOWER('%radar%') OR LOWER(source."name") LIKE LOWER('%missile%') OR LOWER(source."name") LIKE LOWER('%weapons%')) OR source."military" IS NOT NULL OR source."landuse" IN ('military')) THEN 80
    WHEN ((LOWER(source."name") LIKE LOWER('%engineering%') OR LOWER(source."name") LIKE LOWER('%technology%') OR LOWER(source."name") LIKE LOWER('%systems%') OR LOWER(source."name") LIKE LOWER('%electronics%') OR LOWER(source."name") LIKE LOWER('%precision%') OR LOWER(source."name") LIKE LOWER('%advanced%')) OR source."industrial" IN ('engineering','electronics','precision','high_tech') OR source."man_made" IN ('works','factory') OR source."office" IN ('engineering','research','technology') OR source."building" IN ('industrial','factory','warehouse')) THEN 70
    WHEN (source."landuse" IN ('industrial') OR source."building" IN ('industrial','warehouse','manufacture') OR source."industrial" IS NOT NULL) THEN 50
    WHEN ((LOWER(source."name") LIKE LOWER('%research%') OR LOWER(source."name") LIKE LOWER('%development%') OR LOWER(source."name") LIKE LOWER('%laboratory%') OR LOWER(source."name") LIKE LOWER('%institute%') OR LOWER(source."name") LIKE LOWER('%university%')) OR source."office" IN ('research','engineering') OR source."amenity" IN ('research_institute','university')) THEN 60
    ELSE 0
END +
    CASE WHEN ((LOWER(source."name") LIKE LOWER('%boeing%') OR LOWER(source."name") LIKE LOWER('%airbus%') OR LOWER(source."name") LIKE LOWER('%rolls royce%') OR LOWER(source."name") LIKE LOWER('%bae systems%') OR LOWER(source."name") LIKE LOWER('%leonardo%') OR LOWER(source."name") LIKE LOWER('%thales%') OR LOWER(source."name") LIKE LOWER('%safran%')) OR (LOWER(source."operator") LIKE LOWER('%boeing%') OR LOWER(source."operator") LIKE LOWER('%airbus%') OR LOWER(source."operator") LIKE LOWER('%rolls royce%') OR LOWER(source."operator") LIKE LOWER('%bae systems%') OR LOWER(source."operator") LIKE LOWER('%leonardo%') OR LOWER(source."operator") LIKE LOWER('%thales%') OR LOWER(source."operator") LIKE LOWER('%safran%'))) THEN 50 ELSE 0 END +
    CASE WHEN ((LOWER(source."name") LIKE LOWER('%aerospace%') OR LOWER(source."name") LIKE LOWER('%aviation%') OR LOWER(source."name") LIKE LOWER('%aircraft%') OR LOWER(source."name") LIKE LOWER('%avionics%') OR LOWER(source."name") LIKE LOWER('%turbine%') OR LOWER(source."name") LIKE LOWER('%engine%')) OR (LOWER(source."operator") LIKE LOWER('%aerospace%') OR LOWER(source."operator") LIKE LOWER('%aviation%') OR LOWER(source."operator") LIKE LOWER('%aircraft%') OR LOWER(source."operator") LIKE LOWER('%avionics%') OR LOWER(source."operator") LIKE LOWER('%turbine%') OR LOWER(source."operator") LIKE LOWER('%engine%'))) THEN 30 ELSE 0 END +
    CASE WHEN ((LOWER(source."name") LIKE LOWER('%precision%') OR LOWER(source."name") LIKE LOWER('%machining%') OR LOWER(source."name") LIKE LOWER('%casting%') OR LOWER(source."name") LIKE LOWER('%forging%') OR LOWER(source."name") LIKE LOWER('%composite%') OR LOWER(source."name") LIKE LOWER('%materials%')) OR (LOWER(source."operator") LIKE LOWER('%precision%') OR LOWER(source."operator") LIKE LOWER('%machining%') OR LOWER(source."operator") LIKE LOWER('%casting%') OR LOWER(source."operator") LIKE LOWER('%forging%') OR LOWER(source."operator") LIKE LOWER('%composite%') OR LOWER(source."operator") LIKE LOWER('%materials%'))) THEN 20 ELSE 0 END +
    CASE WHEN (source."amenity" IN ('restaurant','pub','cafe','bar','fast_food','fuel','hospital','school') OR source."shop" IS NOT NULL OR source."tourism" IS NOT NULL OR source."leisure" IS NOT NULL OR source."building" IN ('house','apartments','residential','hotel','retail')) THEN -50 ELSE 0 END +
    CASE WHEN (source."landuse" IN ('residential','retail','commercial','farmland')) THEN -25 ELSE 0 END +
    CASE WHEN (source."office" IN ('insurance','finance','estate_agent','lawyer','accountant') OR source."amenity" IN ('bank','post_office','library')) THEN -15 ELSE 0 END
) > 0;
