-- Aerospace Supplier Scoring SQL
-- Generated from scoring.yaml and negative_signals.yaml

-- Scored view for planet_osm_point
DROP VIEW IF EXISTS public.planet_osm_point_aerospace_scored CASCADE;
CREATE VIEW public.planet_osm_point_aerospace_scored AS
SELECT *,
    (CASE WHEN (name ILIKE '%aerospace%' OR name ILIKE '%aviation%' OR name ILIKE '%aircraft%' OR name ILIKE '%airbus%' OR name ILIKE '%boeing%' OR name ILIKE '%bae%' OR name ILIKE '%rolls royce%') THEN 100 ELSE 0 END + CASE WHEN (operator ILIKE '%aerospace%' OR operator ILIKE '%aviation%' OR operator ILIKE '%aircraft%' OR operator ILIKE '%airbus%' OR operator ILIKE '%boeing%' OR operator ILIKE '%bae%' OR operator ILIKE '%rolls royce%') THEN 100 ELSE 0 END + CASE WHEN landuse = 'industrial' THEN 50 ELSE 0 END + CASE WHEN office IS NOT NULL THEN 30 ELSE 0 END + CASE WHEN man_made IN ('works', 'factory', 'tower', 'mast') THEN 25 ELSE 0 END + CASE WHEN (name ILIKE '%technology%' OR name ILIKE '%engineering%' OR name ILIKE '%systems%' OR name ILIKE '%electronics%' OR name ILIKE '%precision%') THEN 35 ELSE 0 END) AS aerospace_score,
    ARRAY[]::text[] AS matched_keywords,
    'planet_osm_point' AS source_table
FROM public.planet_osm_point_aerospace_filtered
WHERE (CASE WHEN (name ILIKE '%aerospace%' OR name ILIKE '%aviation%' OR name ILIKE '%aircraft%' OR name ILIKE '%airbus%' OR name ILIKE '%boeing%' OR name ILIKE '%bae%' OR name ILIKE '%rolls royce%') THEN 100 ELSE 0 END + CASE WHEN (operator ILIKE '%aerospace%' OR operator ILIKE '%aviation%' OR operator ILIKE '%aircraft%' OR operator ILIKE '%airbus%' OR operator ILIKE '%boeing%' OR operator ILIKE '%bae%' OR operator ILIKE '%rolls royce%') THEN 100 ELSE 0 END + CASE WHEN landuse = 'industrial' THEN 50 ELSE 0 END + CASE WHEN office IS NOT NULL THEN 30 ELSE 0 END + CASE WHEN man_made IN ('works', 'factory', 'tower', 'mast') THEN 25 ELSE 0 END + CASE WHEN (name ILIKE '%technology%' OR name ILIKE '%engineering%' OR name ILIKE '%systems%' OR name ILIKE '%electronics%' OR name ILIKE '%precision%') THEN 35 ELSE 0 END) > 0;

-- Scored view for planet_osm_line
DROP VIEW IF EXISTS public.planet_osm_line_aerospace_scored CASCADE;
CREATE VIEW public.planet_osm_line_aerospace_scored AS
SELECT *,
    (CASE WHEN (name ILIKE '%aerospace%' OR name ILIKE '%aviation%' OR name ILIKE '%aircraft%' OR name ILIKE '%airbus%' OR name ILIKE '%boeing%' OR name ILIKE '%bae%' OR name ILIKE '%rolls royce%') THEN 100 ELSE 0 END + CASE WHEN (operator ILIKE '%aerospace%' OR operator ILIKE '%aviation%' OR operator ILIKE '%aircraft%' OR operator ILIKE '%airbus%' OR operator ILIKE '%boeing%' OR operator ILIKE '%bae%' OR operator ILIKE '%rolls royce%') THEN 100 ELSE 0 END + CASE WHEN landuse = 'industrial' THEN 50 ELSE 0 END + CASE WHEN building IN ('industrial', 'warehouse', 'factory', 'office') THEN 40 ELSE 0 END + CASE WHEN office IS NOT NULL THEN 30 ELSE 0 END + CASE WHEN industrial IS NOT NULL THEN 40 ELSE 0 END + CASE WHEN man_made IN ('works', 'factory', 'tower', 'mast') THEN 25 ELSE 0 END + CASE WHEN (name ILIKE '%technology%' OR name ILIKE '%engineering%' OR name ILIKE '%systems%' OR name ILIKE '%electronics%' OR name ILIKE '%precision%') THEN 35 ELSE 0 END) AS aerospace_score,
    ARRAY[]::text[] AS matched_keywords,
    'planet_osm_line' AS source_table
FROM public.planet_osm_line_aerospace_filtered
WHERE (CASE WHEN (name ILIKE '%aerospace%' OR name ILIKE '%aviation%' OR name ILIKE '%aircraft%' OR name ILIKE '%airbus%' OR name ILIKE '%boeing%' OR name ILIKE '%bae%' OR name ILIKE '%rolls royce%') THEN 100 ELSE 0 END + CASE WHEN (operator ILIKE '%aerospace%' OR operator ILIKE '%aviation%' OR operator ILIKE '%aircraft%' OR operator ILIKE '%airbus%' OR operator ILIKE '%boeing%' OR operator ILIKE '%bae%' OR operator ILIKE '%rolls royce%') THEN 100 ELSE 0 END + CASE WHEN landuse = 'industrial' THEN 50 ELSE 0 END + CASE WHEN building IN ('industrial', 'warehouse', 'factory', 'office') THEN 40 ELSE 0 END + CASE WHEN office IS NOT NULL THEN 30 ELSE 0 END + CASE WHEN industrial IS NOT NULL THEN 40 ELSE 0 END + CASE WHEN man_made IN ('works', 'factory', 'tower', 'mast') THEN 25 ELSE 0 END + CASE WHEN (name ILIKE '%technology%' OR name ILIKE '%engineering%' OR name ILIKE '%systems%' OR name ILIKE '%electronics%' OR name ILIKE '%precision%') THEN 35 ELSE 0 END) > 0;

-- Scored view for planet_osm_polygon
DROP VIEW IF EXISTS public.planet_osm_polygon_aerospace_scored CASCADE;
CREATE VIEW public.planet_osm_polygon_aerospace_scored AS
SELECT *,
    (CASE WHEN (name ILIKE '%aerospace%' OR name ILIKE '%aviation%' OR name ILIKE '%aircraft%' OR name ILIKE '%airbus%' OR name ILIKE '%boeing%' OR name ILIKE '%bae%' OR name ILIKE '%rolls royce%') THEN 100 ELSE 0 END + CASE WHEN (operator ILIKE '%aerospace%' OR operator ILIKE '%aviation%' OR operator ILIKE '%aircraft%' OR operator ILIKE '%airbus%' OR operator ILIKE '%boeing%' OR operator ILIKE '%bae%' OR operator ILIKE '%rolls royce%') THEN 100 ELSE 0 END + CASE WHEN landuse = 'industrial' THEN 50 ELSE 0 END + CASE WHEN building IN ('industrial', 'warehouse', 'factory', 'office') THEN 40 ELSE 0 END + CASE WHEN office IS NOT NULL THEN 30 ELSE 0 END + CASE WHEN industrial IS NOT NULL THEN 40 ELSE 0 END + CASE WHEN man_made IN ('works', 'factory', 'tower', 'mast') THEN 25 ELSE 0 END + CASE WHEN (name ILIKE '%technology%' OR name ILIKE '%engineering%' OR name ILIKE '%systems%' OR name ILIKE '%electronics%' OR name ILIKE '%precision%') THEN 35 ELSE 0 END) AS aerospace_score,
    ARRAY[]::text[] AS matched_keywords,
    'planet_osm_polygon' AS source_table
FROM public.planet_osm_polygon_aerospace_filtered
WHERE (CASE WHEN (name ILIKE '%aerospace%' OR name ILIKE '%aviation%' OR name ILIKE '%aircraft%' OR name ILIKE '%airbus%' OR name ILIKE '%boeing%' OR name ILIKE '%bae%' OR name ILIKE '%rolls royce%') THEN 100 ELSE 0 END + CASE WHEN (operator ILIKE '%aerospace%' OR operator ILIKE '%aviation%' OR operator ILIKE '%aircraft%' OR operator ILIKE '%airbus%' OR operator ILIKE '%boeing%' OR operator ILIKE '%bae%' OR operator ILIKE '%rolls royce%') THEN 100 ELSE 0 END + CASE WHEN landuse = 'industrial' THEN 50 ELSE 0 END + CASE WHEN building IN ('industrial', 'warehouse', 'factory', 'office') THEN 40 ELSE 0 END + CASE WHEN office IS NOT NULL THEN 30 ELSE 0 END + CASE WHEN industrial IS NOT NULL THEN 40 ELSE 0 END + CASE WHEN man_made IN ('works', 'factory', 'tower', 'mast') THEN 25 ELSE 0 END + CASE WHEN (name ILIKE '%technology%' OR name ILIKE '%engineering%' OR name ILIKE '%systems%' OR name ILIKE '%electronics%' OR name ILIKE '%precision%') THEN 35 ELSE 0 END) > 0;

-- Scored view for planet_osm_roads
DROP VIEW IF EXISTS public.planet_osm_roads_aerospace_scored CASCADE;
CREATE VIEW public.planet_osm_roads_aerospace_scored AS
SELECT *,
    (CASE WHEN (name ILIKE '%aerospace%' OR name ILIKE '%aviation%' OR name ILIKE '%aircraft%' OR name ILIKE '%airbus%' OR name ILIKE '%boeing%' OR name ILIKE '%bae%' OR name ILIKE '%rolls royce%') THEN 100 ELSE 0 END + CASE WHEN (operator ILIKE '%aerospace%' OR operator ILIKE '%aviation%' OR operator ILIKE '%aircraft%' OR operator ILIKE '%airbus%' OR operator ILIKE '%boeing%' OR operator ILIKE '%bae%' OR operator ILIKE '%rolls royce%') THEN 100 ELSE 0 END + CASE WHEN landuse = 'industrial' THEN 50 ELSE 0 END + CASE WHEN building IN ('industrial', 'warehouse', 'factory', 'office') THEN 40 ELSE 0 END + CASE WHEN office IS NOT NULL THEN 30 ELSE 0 END + CASE WHEN industrial IS NOT NULL THEN 40 ELSE 0 END + CASE WHEN man_made IN ('works', 'factory', 'tower', 'mast') THEN 25 ELSE 0 END + CASE WHEN (name ILIKE '%technology%' OR name ILIKE '%engineering%' OR name ILIKE '%systems%' OR name ILIKE '%electronics%' OR name ILIKE '%precision%') THEN 35 ELSE 0 END) AS aerospace_score,
    ARRAY[]::text[] AS matched_keywords,
    'planet_osm_roads' AS source_table
FROM public.planet_osm_roads_aerospace_filtered
WHERE (CASE WHEN (name ILIKE '%aerospace%' OR name ILIKE '%aviation%' OR name ILIKE '%aircraft%' OR name ILIKE '%airbus%' OR name ILIKE '%boeing%' OR name ILIKE '%bae%' OR name ILIKE '%rolls royce%') THEN 100 ELSE 0 END + CASE WHEN (operator ILIKE '%aerospace%' OR operator ILIKE '%aviation%' OR operator ILIKE '%aircraft%' OR operator ILIKE '%airbus%' OR operator ILIKE '%boeing%' OR operator ILIKE '%bae%' OR operator ILIKE '%rolls royce%') THEN 100 ELSE 0 END + CASE WHEN landuse = 'industrial' THEN 50 ELSE 0 END + CASE WHEN building IN ('industrial', 'warehouse', 'factory', 'office') THEN 40 ELSE 0 END + CASE WHEN office IS NOT NULL THEN 30 ELSE 0 END + CASE WHEN industrial IS NOT NULL THEN 40 ELSE 0 END + CASE WHEN man_made IN ('works', 'factory', 'tower', 'mast') THEN 25 ELSE 0 END + CASE WHEN (name ILIKE '%technology%' OR name ILIKE '%engineering%' OR name ILIKE '%systems%' OR name ILIKE '%electronics%' OR name ILIKE '%precision%') THEN 35 ELSE 0 END) > 0;
